base_dir: "/path/to/data/airevolve030326/v2"
tasks: ["backandforth", "figure8", "circle"]
genotypes: ["spherical", "cppn", "hybrid_cppn"]
figures_subdir: "figures_MuPlusLambda"
n_workers: 24

# Style overrides (defaults in plot_utils.py if omitted)
style:
  axis_label_fontsize: 30
  tick_label_fontsize: 30
  legend_fontsize: 30
  annotation_fontsize: 12
  dpi: 300

y_limits:
  max_fitness: 30
  mean_fitness: 30
  median_max_fitness: 30
  median_mean_fitness: 30
  diversity: 5
  genome_diversity: 12.5
  combined_divergence_ratio: 4.25
  bloodline_phenotypic_divergence: 6
  bloodline_genotypic_divergence: 11
  phenotypic_distance: 7


collectors:
  - morphological_descriptors
  - fitness_diversity
  - best_individual
  - bloodline
  - learning_descriptors
  - genome_diversity
  - genotypic_descriptors
  - inter_run_diversity
  - top_k_diversity
  - convergence_speed
  - population_divergence

plotters:
  - fitness_diversity
  - morphological_descriptors
  - morphological_descriptors_against_fitness
  - learning_descriptors
  - bloodline
  - genome_diversity
  - genotypic_descriptors
  - inter_run_diversity
  - top_k_diversity
  - best_individual
  - best_evaluations
  # - genome_visualization
  - convergence_speed
  - population_divergence
