#!/usr/bin/env python3
"""Generate LaTeX figure and table code for a paper comparing three
drone morphology representations (Spherical, CPPN, Hybrid).

Produces a curated, paper-structured .tex file organised by narrative
section rather than a flat dump of every generated plot.

Usage:
    python -m experimentation.generate_latex_figures
    python -m experimentation.generate_latex_figures --base-dir /path/to/data
"""

import argparse
import os

from experimentation.config import BASE_DIR, TASK_LABELS

# ── Ordered task list (controls figure ordering) ─────────────────────────────
TASKS = ["backandforth", "figure8", "circle"]

# ── Helper paths ─────────────────────────────────────────────────────────────

def _fig(task, plotter, name):
    """Return relative PDF path for a figure."""
    return f"figures/{task}/{plotter}/{name}.pdf"


def _cross(plotter, name):
    """Return relative PDF path for a cross-task figure."""
    return _fig("cross_task", plotter, name)


# ── LaTeX building blocks ────────────────────────────────────────────────────

def _sanitize(s):
    return s.replace(" ", "_").replace("/", "_").replace("-", "_").lower()


def _subfig(path, caption, width, label):
    return (
        f"    \\begin{{subfigure}}{{{width}\\textwidth}}\n"
        f"        \\centering\n"
        f"        \\includegraphics[width=\\textwidth]{{{path}}}\n"
        f"        \\caption{{{caption}}}\n"
        f"        \\label{{fig:{label}}}\n"
        f"    \\end{{subfigure}}"
    )


def _figure(path, caption, label, width="0.85\\textwidth"):
    return (
        f"\\begin{{figure}}[htbp]\n"
        f"    \\centering\n"
        f"    \\includegraphics[width={width}]{{{path}}}\n"
        f"    \\caption{{{caption}}}\n"
        f"    \\label{{fig:{label}}}\n"
        f"\\end{{figure}}"
    )


def _input_table(path, caption, label):
    """Input an external .tex significance table with surrounding table env."""
    return (
        f"\\begin{{table}}[htbp]\n"
        f"    \\centering\n"
        f"    \\caption{{{caption}}}\n"
        f"    \\label{{tab:{label}}}\n"
        f"    \\input{{{path}}}\n"
        f"\\end{{table}}"
    )


def _grouped_figure(subfigs, caption, label, cols=3):
    """Build a figure environment with multiple subfigures."""
    lines = [
        "\\begin{figure*}[htbp]",
        "    \\centering",
    ]
    for i, (path, sub_caption, sub_label, width) in enumerate(subfigs):
        lines.append(_subfig(path, sub_caption, width, sub_label))
        if (i + 1) % cols == 0 and i + 1 < len(subfigs):
            lines.append("    \\\\[6pt]")
        elif i + 1 < len(subfigs):
            lines.append("    \\hfill")
    lines.append(f"    \\caption{{{caption}}}")
    lines.append(f"    \\label{{fig:{label}}}")
    lines.append("\\end{figure*}")
    return "\n".join(lines)


def _cross_task_subfigures(plotter, filename, _caption_template, label_prefix,
                           width="0.32"):
    """Create a 3-subfigure row: one per task."""
    subfigs = []
    for task in TASKS:
        task_label = TASK_LABELS[task]
        path = _fig(task, plotter, filename)
        subfigs.append((
            path,
            task_label,
            f"{label_prefix}_{_sanitize(task)}",
            width,
        ))
    return subfigs


def _section(title):
    return f"\n% {'=' * 70}\n% {title}\n% {'=' * 70}\n"


def _subsection(title):
    return f"\n% ── {title} {'─' * max(1, 60 - len(title))}\n"


# ── File existence checker ───────────────────────────────────────────────────

def _exists(base, relpath):
    """Check whether a figure PDF exists on disk."""
    return os.path.isfile(os.path.join(base, "output", relpath))


# ── Main generator ───────────────────────────────────────────────────────────

def generate_latex(base_dir=None):
    """Generate a curated, paper-structured LaTeX file."""
    base = base_dir or BASE_DIR
    figures_root = os.path.join(base, "output", "figures")

    if not os.path.isdir(figures_root):
        print(f"No figures directory found at {figures_root}")
        return

    def exists(relpath):
        return _exists(base, relpath)

    lines = [
        "% Auto-generated by generate_latex_figures.py",
        "% Paper-structured LaTeX for: Comparing Drone Morphology Representations",
        "% Include with: \\input{paper_figures.tex}",
        "%",
        "% Requires packages: graphicx, subcaption, booktabs",
        "",
    ]
    skipped = []

    def add(text):
        lines.append(text)
        lines.append("")

    def add_if(relpath, text):
        if exists(relpath):
            add(text)
        else:
            skipped.append(relpath)

    # ═════════════════════════════════════════════════════════════════════════
    # SECTION 1: FITNESS RESULTS (the core result)
    # ═════════════════════════════════════════════════════════════════════════
    add(_section("SECTION: FITNESS RESULTS"))

    # --- 1a. Fitness curves across tasks (max + mean + diversity) ---
    add(_subsection("Fitness and diversity evolution per task"))

    for task in TASKS:
        task_label = TASK_LABELS[task]
        tk = _sanitize(task)

        subfigs = [
            (_fig(task, "fitness_diversity", "max_fitness"),
             "Maximum fitness", f"max_fitness_{tk}", "0.32"),
            (_fig(task, "fitness_diversity", "mean_fitness"),
             "Mean fitness", f"mean_fitness_{tk}", "0.32"),
            (_fig(task, "fitness_diversity", "diversity"),
             "Phenotypic diversity", f"diversity_{tk}", "0.32"),
        ]
        all_exist = all(exists(s[0]) for s in subfigs)
        if all_exist:
            add(_grouped_figure(
                subfigs,
                f"Fitness and phenotypic diversity over generations for the "
                f"{task_label} task. Shaded regions show interquartile range "
                f"across independent runs.",
                f"fitness_diversity_{tk}",
                cols=3,
            ))
        else:
            for s in subfigs:
                if not exists(s[0]):
                    skipped.append(s[0])

    # --- 1b. Median max fitness box plots per task ---
    add(_subsection("Final generation fitness box plots"))

    subfigs = _cross_task_subfigures(
        "fitness_diversity", "median_max_fitness",
        "Median max fitness — {task}", "median_max",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Distribution of per-run maximum fitness at the final generation "
            "across tasks. The Hybrid representation achieves the highest "
            "median and lowest variance.",
            "median_max_fitness_all",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # --- 1c. Cross-task significance tables ---
    add(_subsection("Cross-task statistical significance"))

    sig_path = "figures/cross_task/fitness_diversity/cross_task_significance.tex"
    add_if(sig_path, _input_table(
        sig_path,
        "Cross-task pairwise significance tests (Fisher's combined $p$-values "
        "with Bonferroni correction). The Hybrid representation significantly "
        "outperforms both Spherical and CPPN on mean fitness.",
        "cross_task_significance",
    ))

    # Per-task significance tables
    for task in TASKS:
        task_label = TASK_LABELS[task]
        tk = _sanitize(task)
        path = f"figures/{task}/fitness_diversity/significance_table.tex"
        add_if(path, _input_table(
            path,
            f"Pairwise significance tests for fitness metrics — "
            f"{task_label} task.",
            f"significance_{tk}",
        ))

    # ═════════════════════════════════════════════════════════════════════════
    # SECTION 2: WHY HYBRID WINS — MORPHOLOGICAL DESCRIPTORS
    # ═════════════════════════════════════════════════════════════════════════
    add(_section("SECTION: MORPHOLOGICAL ANALYSIS"))

    # Key descriptors that explain the fitness advantage
    key_morpho = [
        ("thrust_alignment",
         "Thrust alignment",
         "Number of motors with thrust vectors aligned to the body $z$-axis. "
         "Higher values indicate more motors contributing to vertical lift."),
        ("max_thrust_to_weight",
         "Thrust-to-weight ratio",
         "Maximum thrust-to-weight ratio. Designs below 1.0 cannot sustain "
         "hover. The Spherical representation evolves significantly lower "
         "ratios."),
        ("proportion",
         "Arm proportion",
         "Ratio of mean arm length to body radius. Longer arms provide "
         "greater control authority through increased moment arms."),
        ("controlability",
         "Controllability",
         "Condition number of the allocation matrix (lower is better). "
         "Hybrid and CPPN designs are significantly more controllable "
         "than Spherical."),
        ("f_force",
         "Force utilisation",
         "Fraction of maximum motor force aligned with the body $z$-axis. "
         "Values near 1.0 indicate well-oriented motor configurations."),
        ("f_torque",
         "Torque capability",
         "Fraction of motor force available for yaw torque generation. "
         "Lower values indicate more force dedicated to lift."),
    ]

    add(_subsection("Key morphological descriptors per task"))

    for filename, short_name, long_caption in key_morpho:
        subfigs = _cross_task_subfigures(
            "morphological_descriptors", filename,
            f"{short_name} — {{task}}", _sanitize(filename),
        )
        all_exist = all(exists(s[0]) for s in subfigs)
        if all_exist:
            add(_grouped_figure(
                subfigs,
                f"{long_caption}",
                f"morpho_{_sanitize(filename)}",
                cols=3,
            ))
        else:
            for s in subfigs:
                if not exists(s[0]):
                    skipped.append(s[0])

    # --- Symmetry descriptors ---
    add(_subsection("Symmetry descriptors"))

    for filename, short_name in [
        ("bilateral_asymmetry", "Bilateral asymmetry"),
        ("central_asymmetry", "Central asymmetry"),
    ]:
        subfigs = _cross_task_subfigures(
            "morphological_descriptors", filename,
            f"{short_name} — {{task}}", _sanitize(filename),
        )
        all_exist = all(exists(s[0]) for s in subfigs)
        if all_exist:
            add(_grouped_figure(
                subfigs,
                f"{short_name} over generations across tasks. CPPN-based "
                f"representations produce higher central asymmetry due to "
                f"position-dependent motor configurations.",
                f"morpho_{_sanitize(filename)}",
                cols=3,
            ))
        else:
            for s in subfigs:
                if not exists(s[0]):
                    skipped.append(s[0])

    # --- Hover fitness (sub-component) ---
    add(_subsection("Hovering capability"))

    subfigs = _cross_task_subfigures(
        "morphological_descriptors", "hover_fitness",
        "Hover fitness — {task}", "hover_fitness",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Hover fitness component across tasks. All representations "
            "achieve comparable hovering performance, confirming that "
            "fitness differences arise from trajectory-following rather "
            "than basic flight stability.",
            "morpho_hover_fitness",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # --- Gates passed ---
    add(_subsection("Task completion (gates passed)"))

    subfigs = _cross_task_subfigures(
        "morphological_descriptors", "gates_passed",
        "Gates passed — {task}", "gates_passed",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Number of trajectory gates passed at the final generation. "
            "The Hybrid representation completes significantly more "
            "of the prescribed trajectory than both alternatives.",
            "morpho_gates_passed",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # ═════════════════════════════════════════════════════════════════════════
    # SECTION 3: DIVERSITY ANALYSIS
    # ═════════════════════════════════════════════════════════════════════════
    add(_section("SECTION: DIVERSITY ANALYSIS"))

    # --- 3a. Genotypic vs phenotypic diversity correlation ---
    add(_subsection("Genotypic--phenotypic diversity relationship"))

    for task in TASKS:
        task_label = TASK_LABELS[task]
        tk = _sanitize(task)
        subfigs = []
        for geno, geno_label in [("spherical", "Spherical"),
                                  ("cppn", "CPPN"),
                                  ("hybrid_cppn", "Hybrid")]:
            path = _fig(task, "genome_diversity",
                        f"genotypic_vs_phenotypic_{geno}")
            subfigs.append((
                path,
                geno_label,
                f"gvp_{tk}_{_sanitize(geno)}",
                "0.32",
            ))
        all_exist = all(exists(s[0]) for s in subfigs)
        if all_exist:
            add(_grouped_figure(
                subfigs,
                f"Genotypic vs.\\ phenotypic diversity for the {task_label} "
                f"task. Spherical shows perfect correlation ($r=1.0$) since "
                f"genotype directly encodes phenotype. CPPN and Hybrid show "
                f"near-zero correlation, indicating genotypic neutrality in "
                f"indirect encodings.",
                f"gvp_{tk}",
                cols=3,
            ))
        else:
            for s in subfigs:
                if not exists(s[0]):
                    skipped.append(s[0])

    # --- 3b. Cross-task genome diversity comparison ---
    add(_subsection("Genome diversity across tasks"))

    path = _cross("genome_diversity", "genome_diversity_cross_task")
    add_if(path, _figure(
        path,
        "Genotypic diversity at the final generation across tasks. "
        "CPPN maintains the highest genotypic diversity, but this does "
        "not translate to superior fitness. Hybrid achieves the lowest "
        "genotypic diversity yet the best performance, suggesting "
        "efficient convergence to good solutions.",
        "genome_diversity_cross_task",
    ))

    # --- 3c. Phenotypic diversity curves per task ---
    add(_subsection("Phenotypic diversity evolution"))

    subfigs = _cross_task_subfigures(
        "fitness_diversity", "diversity",
        "Phenotypic diversity — {task}", "pheno_div",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Phenotypic (edit distance) diversity over generations. CPPN "
            "maintains significantly higher phenotypic diversity than both "
            "alternatives (large effect, $p < 0.0001$).",
            "phenotypic_diversity_all",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # --- 3d. Genome diversity curves per task ---
    add(_subsection("Genotypic diversity evolution"))

    subfigs = _cross_task_subfigures(
        "genome_diversity", "genome_diversity_over_generations",
        "Genome diversity — {task}", "geno_div",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Genotypic diversity over generations. Spherical starts high "
            "(random initialisation covers the parameter space) and declines, "
            "while CPPN diversity grows as network topologies diverge.",
            "genotypic_diversity_all",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # ═════════════════════════════════════════════════════════════════════════
    # SECTION 4: INTER-RUN DIVERGENCE AND REPRODUCIBILITY
    # ═════════════════════════════════════════════════════════════════════════
    add(_section("SECTION: INTER-RUN DIVERGENCE"))

    # --- Divergence ratio heatmap ---
    add(_subsection("Cross-task divergence ratio"))

    path = _cross("inter_run_diversity", "divergence_ratio_heatmap")
    add_if(path, _figure(
        path,
        "Inter-run divergence ratio across tasks and representations. "
        "Higher values indicate that independent runs converge to more "
        "diverse final populations. Spherical shows the highest "
        "inter-run divergence ($\\approx 3.5$), suggesting sensitivity "
        "to initial conditions, while CPPN shows the lowest "
        "($\\approx 1.5$).",
        "divergence_heatmap",
    ))

    # --- Top-K cross-run diversity ---
    path = _cross("top_k_diversity", "top_k_diversity_comparison")
    add_if(path, _figure(
        path,
        "Mean phenotypic distance among the top-$k$ individuals from "
        "independent runs. Higher values indicate that each run discovers "
        "distinct high-quality solutions. Hybrid produces the most diverse "
        "elite solutions across runs.",
        "top_k_diversity",
    ))

    # --- Per-task divergence curves ---
    add(_subsection("Divergence ratio evolution"))

    subfigs = _cross_task_subfigures(
        "inter_run_diversity", "divergence_ratio_over_generations",
        "Divergence ratio — {task}", "div_ratio",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Inter-run divergence ratio over generations. Spherical "
            "diverges most, indicating it finds qualitatively different "
            "local optima across runs.",
            "divergence_ratio_all",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # ═════════════════════════════════════════════════════════════════════════
    # SECTION 5: CPPN NETWORK COMPLEXITY
    # ═════════════════════════════════════════════════════════════════════════
    add(_section("SECTION: CPPN NETWORK COMPLEXITY"))

    add(_subsection("Network complexity per task"))

    for task in TASKS:
        task_label = TASK_LABELS[task]
        tk = _sanitize(task)
        subfigs = [
            (_fig(task, "genotypic_descriptors",
                  "n_hidden_nodes_over_generations"),
             "Hidden nodes", f"hidden_{tk}", "0.32"),
            (_fig(task, "genotypic_descriptors",
                  "n_enabled_connections_over_generations"),
             "Enabled connections", f"connections_{tk}", "0.32"),
            (_fig(task, "genotypic_descriptors",
                  "connection_density_over_generations"),
             "Connection density", f"density_{tk}", "0.32"),
        ]
        all_exist = all(exists(s[0]) for s in subfigs)
        if all_exist:
            add(_grouped_figure(
                subfigs,
                f"CPPN network complexity over generations for the "
                f"{task_label} task. Pure CPPN evolves more complex "
                f"networks than Hybrid, which offloads arm geometry to "
                f"the direct encoding.",
                f"cppn_complexity_{tk}",
                cols=3,
            ))
        else:
            for s in subfigs:
                if not exists(s[0]):
                    skipped.append(s[0])

    # Cross-task summary
    add(_subsection("Cross-task network complexity"))

    cross_geno = [
        ("n_hidden_nodes_cross_task", "Hidden nodes"),
        ("n_enabled_connections_cross_task", "Enabled connections"),
        ("longest_path_cross_task", "Longest path"),
    ]
    subfigs = []
    for filename, sub_cap in cross_geno:
        path = _cross("genotypic_descriptors", filename)
        subfigs.append((
            path,
            sub_cap,
            f"cross_{_sanitize(filename)}",
            "0.32",
        ))
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "CPPN network complexity at the final generation across tasks. "
            "Hybrid uses significantly simpler networks (fewer hidden nodes "
            "and connections) than pure CPPN, demonstrating that the direct "
            "encoding component reduces the burden on the neural network.",
            "cppn_complexity_cross",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # ═════════════════════════════════════════════════════════════════════════
    # SECTION 6: BLOODLINE ANALYSIS
    # ═════════════════════════════════════════════════════════════════════════
    add(_section("SECTION: BLOODLINE ANALYSIS"))

    subfigs = _cross_task_subfigures(
        "bloodline", "bloodline_divergence_over_generations",
        "Bloodline divergence — {task}", "bloodline_div",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Phenotypic divergence of the surviving bloodline from its "
            "founder over generations. CPPN lineages accumulate the most "
            "phenotypic change, while Spherical lineages remain closest "
            "to their founders, consistent with the direct encoding's "
            "smaller mutational steps.",
            "bloodline_divergence_all",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # ═════════════════════════════════════════════════════════════════════════
    # SECTION 7: CONVERGENCE SPEED (brief — mostly non-significant)
    # ═════════════════════════════════════════════════════════════════════════
    add(_section("SECTION: CONVERGENCE SPEED (SUPPLEMENTARY)"))

    add(_subsection("Generation to fitness thresholds"))

    subfigs = _cross_task_subfigures(
        "convergence_speed", "gen_to_threshold",
        "Generations to threshold — {task}", "conv_thresh",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Generations required to reach 50\\%, 75\\%, and 90\\% of "
            "final fitness. No significant differences were found between "
            "representations, indicating that the Hybrid's advantage lies "
            "in the quality of its final solutions rather than convergence "
            "speed.",
            "convergence_thresholds",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # Normalised AUC
    add(_subsection("Normalised area under the fitness curve"))

    subfigs = _cross_task_subfigures(
        "convergence_speed", "auc_normalized",
        "Normalised AUC — {task}", "auc",
    )
    all_exist = all(exists(s[0]) for s in subfigs)
    if all_exist:
        add(_grouped_figure(
            subfigs,
            "Normalised area under the fitness curve. Values near 1.0 "
            "indicate rapid convergence to the final fitness level.",
            "auc_all",
            cols=3,
        ))
    else:
        for s in subfigs:
            if not exists(s[0]):
                skipped.append(s[0])

    # ═════════════════════════════════════════════════════════════════════════
    # SECTION 8: LEARNING DESCRIPTORS (SUPPLEMENTARY — no differences)
    # ═════════════════════════════════════════════════════════════════════════
    add(_section("SECTION: CONTROLLER TUNING (SUPPLEMENTARY)"))

    add(_subsection("Learning descriptors per task"))

    for task in TASKS:
        task_label = TASK_LABELS[task]
        tk = _sanitize(task)
        subfigs = [
            (_fig(task, "learning_descriptors", "learning_delta"),
             "Learning delta", f"ldelta_{tk}", "0.48"),
            (_fig(task, "learning_descriptors", "asymptotic_performance"),
             "Asymptotic perf.", f"lasymptotic_{tk}", "0.48"),
        ]
        all_exist = all(exists(s[0]) for s in subfigs)
        if all_exist:
            add(_grouped_figure(
                subfigs,
                f"CMA-ES controller tuning descriptors for the {task_label} "
                f"task. No significant differences between representations "
                f"were found, confirming that fitness advantages arise from "
                f"morphology rather than controller optimisation.",
                f"learning_{tk}",
                cols=2,
            ))
        else:
            for s in subfigs:
                if not exists(s[0]):
                    skipped.append(s[0])

    # ═════════════════════════════════════════════════════════════════════════
    # Write output
    # ═════════════════════════════════════════════════════════════════════════
    latex_dir = os.path.join(base, "output", "latex")
    os.makedirs(latex_dir, exist_ok=True)
    out_path = os.path.join(latex_dir, "paper_figures.tex")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Saved: {out_path}")
    content = "\n".join(lines)
    n_figures = content.count("\\end{figure*}") + content.count("\\end{figure}")
    n_tables = content.count("\\end{table}")
    print(f"  {n_figures} figures, {n_tables} tables")
    if skipped:
        print(f"  {len(skipped)} missing files skipped:")
        for s in skipped[:10]:
            print(f"    - {s}")
        if len(skipped) > 10:
            print(f"    ... and {len(skipped) - 10} more")


def main():
    parser = argparse.ArgumentParser(
        description="Generate paper-structured LaTeX figures and tables")
    parser.add_argument("--base-dir", default=BASE_DIR,
                        help="Base experiment data directory")
    args = parser.parse_args()
    generate_latex(args.base_dir)


if __name__ == "__main__":
    main()
