"""
Script to load and plot fitness and diversity data from CSV files
generated by the data collection script.
Enhanced to support 2D arrays of experiment names with custom colors.
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from itertools import combinations
from typing import Dict, List, Optional, Union
from scipy.stats import mannwhitneyu, combine_pvalues


def load_experiment_data(data_dir: str, experiment_names: Union[List[str], List[List[str]]]) -> Dict[str, pd.DataFrame]:
    """Load fitness and diversity data for multiple experiments."""
    experiment_data = {}
    
    # Flatten experiment_names if it's a 2D array
    flat_experiment_names = []
    if isinstance(experiment_names[0], list):
        for row in experiment_names:
            flat_experiment_names.extend(row)
    else:
        flat_experiment_names = experiment_names
    
    for experiment_name in flat_experiment_names:
        csv_path = os.path.join(data_dir, experiment_name, "fitness_diversity_data.csv")
        
        if os.path.exists(csv_path):
            df = pd.read_csv(csv_path)
            experiment_data[experiment_name] = df
            print(f"Loaded data for {experiment_name}: {len(df)} rows")
        else:
            print(f"Warning: Data file not found for {experiment_name} at {csv_path}")
    
    return experiment_data


def aggregate_runs_by_generation(df: pd.DataFrame) -> Dict[str, np.ndarray]:
    """Aggregate fitness and diversity data across runs for each generation."""
    # Group by generation and collect data across all runs
    grouped = df.groupby('generation')
    
    # Find the maximum number of runs across all generations
    max_runs = 0
    for gen, group in grouped:
        max_runs = max(max_runs, len(group))
    
    max_generation = df['generation'].max()
    
    # Initialize arrays with NaN values
    max_fitness_array = np.full((max_generation + 1, max_runs), np.nan)
    mean_fitness_array = np.full((max_generation + 1, max_runs), np.nan)
    std_fitness_array = np.full((max_generation + 1, max_runs), np.nan)
    diversity_array = np.full((max_generation + 1, max_runs), np.nan)
    
    # Fill in the data where it exists
    for gen, group in grouped:
        for idx, (_, row) in enumerate(group.iterrows()):
            if idx < max_runs:  # Only fill up to max_runs to avoid index errors
                max_fitness_array[gen, idx] = row['max_fitness']
                mean_fitness_array[gen, idx] = row['mean_fitness']
                std_fitness_array[gen, idx] = row['std_fitness']
                diversity_array[gen, idx] = row['diversity']
    
    return {
        'max_fitness': max_fitness_array,
        'mean_fitness': mean_fitness_array,
        'std_fitness': std_fitness_array,
        'diversity': diversity_array
    }


def calculate_fitness_improvement(experiment_data: Dict[str, pd.DataFrame]) -> Dict[str, Dict[str, float]]:
    """
    Calculate the percentage improvement in average max fitness from first to last generation.
    Returns a dictionary with improvement statistics for each experiment.
    """
    improvement_stats = {}
    
    for exp_name, df in experiment_data.items():
        # Get first generation data (generation 0)
        first_gen_data = df[df['generation'] == 0]
        # Get last generation data
        last_gen = df['generation'].max()
        last_gen_data = df[df['generation'] == last_gen]
        
        if len(first_gen_data) == 0 or len(last_gen_data) == 0:
            print(f"Warning: Missing data for first or last generation in {exp_name}")
            continue
        
        # Calculate average max fitness for first and last generations
        first_gen_avg_max_fitness = first_gen_data['max_fitness'].mean()
        last_gen_avg_max_fitness = last_gen_data['max_fitness'].mean()
        
        # Handle cases where first generation fitness might be zero or negative
        if first_gen_avg_max_fitness == 0:
            if last_gen_avg_max_fitness == 0:
                percentage_increase = 0.0
            else:
                percentage_increase = float('inf')  # Infinite improvement
        elif first_gen_avg_max_fitness < 0 and last_gen_avg_max_fitness < 0:
            # Both negative: improvement means getting closer to zero (less negative)
            percentage_increase = ((first_gen_avg_max_fitness - last_gen_avg_max_fitness) / abs(first_gen_avg_max_fitness)) * 100
        elif first_gen_avg_max_fitness < 0 and last_gen_avg_max_fitness >= 0:
            # Went from negative to positive or zero
            percentage_increase = ((last_gen_avg_max_fitness - first_gen_avg_max_fitness) / abs(first_gen_avg_max_fitness)) * 100
        else:
            # Standard case: both positive
            percentage_increase = ((last_gen_avg_max_fitness - first_gen_avg_max_fitness) / first_gen_avg_max_fitness) * 100
        
        improvement_stats[exp_name] = {
            'first_gen_avg_max_fitness': first_gen_avg_max_fitness,
            'last_gen_avg_max_fitness': last_gen_avg_max_fitness,
            'percentage_increase': percentage_increase,
            'absolute_improvement': last_gen_avg_max_fitness - first_gen_avg_max_fitness,
            'first_generation': 0,
            'last_generation': last_gen
        }
    
    return improvement_stats


def generate_latex_table(improvement_stats: Dict[str, Dict[str, float]], save_path: Optional[str] = None) -> str:
    """
    Generate a LaTeX table from fitness improvement statistics.
    
    Args:
        improvement_stats: Dictionary containing improvement statistics for each experiment
        save_path: Optional path to save the LaTeX table to a .tex file
    
    Returns:
        String containing the LaTeX table code
    """
    
    # Start building the LaTeX table
    latex_lines = []
    latex_lines.append("\\begin{table}[htbp]")
    latex_lines.append("\\centering")
    latex_lines.append("\\caption{Fitness Improvement Summary}")
    latex_lines.append("\\label{tab:fitness_improvement}")
    latex_lines.append("\\begin{tabular}{|l|c|c|c|c|}")
    latex_lines.append("\\hline")
    latex_lines.append("\\textbf{Experiment} & \\textbf{First Gen} & \\textbf{Last Gen} & \\textbf{Improvement} & \\textbf{Percentage} \\\\")
    latex_lines.append("\\hline")
    
    # Add data rows
    for exp_name, stats in improvement_stats.items():
        # Clean up experiment name for LaTeX (replace underscores)
        clean_exp_name = exp_name.replace('_', '\\_')
        
        first_gen = stats['first_gen_avg_max_fitness']
        last_gen = stats['last_gen_avg_max_fitness']
        improvement = stats['absolute_improvement']
        
        if stats['percentage_increase'] == float('inf'):
            percentage = "Infinite"
        else:
            percentage = f"{stats['percentage_increase']:.2f}\\%"
        
        latex_lines.append(f"{clean_exp_name} & {first_gen:.4f} & {last_gen:.4f} & {improvement:.4f} & {percentage} \\\\")
        latex_lines.append("\\hline")
    
    latex_lines.append("\\end{tabular}")
    latex_lines.append("\\end{table}")
    
    # Join all lines
    latex_table = "\n".join(latex_lines)
    
    # Save to file if path provided
    if save_path:
        latex_file_path = os.path.join(save_path, "fitness_improvement_table.tex")
        with open(latex_file_path, 'w') as f:
            f.write(latex_table)
        print(f"LaTeX table saved to: {latex_file_path}")
    
    return latex_table


def print_fitness_improvement_summary(improvement_stats: Dict[str, Dict[str, float]]):
    """Print a formatted summary of fitness improvements for all experiments."""
    
    print("\n" + "="*80)
    print("FITNESS IMPROVEMENT SUMMARY")
    print("="*80)
    
    for exp_name, stats in improvement_stats.items():
        print(f"\nExperiment: {exp_name}")
        print(f"{'='*len(exp_name)}=========")
        print(f"First Generation (Gen {stats['first_generation']}) Avg Max Fitness: {stats['first_gen_avg_max_fitness']:.4f}")
        print(f"Last Generation (Gen {stats['last_generation']}) Avg Max Fitness:  {stats['last_gen_avg_max_fitness']:.4f}")
        print(f"Absolute Improvement: {stats['absolute_improvement']:.4f}")
        
        if stats['percentage_increase'] == float('inf'):
            print(f"Percentage Increase: Infinite (improved from 0)")
        else:
            print(f"Percentage Increase: {stats['percentage_increase']:.2f}%")
    
    print("\n" + "="*80)
    
    # Create a summary table
    if improvement_stats:
        print("\nSUMMARY TABLE:")
        print("-" * 100)
        print(f"{'Experiment':<20} {'First Gen':<12} {'Last Gen':<12} {'Improvement':<12} {'Percentage':<12}")
        print("-" * 100)
        
        for exp_name, stats in improvement_stats.items():
            if stats['percentage_increase'] == float('inf'):
                pct_str = "Infinite"
            else:
                pct_str = f"{stats['percentage_increase']:.2f}%"
            
            print(f"{exp_name:<20} {stats['first_gen_avg_max_fitness']:<12.4f} "
                  f"{stats['last_gen_avg_max_fitness']:<12.4f} "
                  f"{stats['absolute_improvement']:<12.4f} {pct_str:<12}")
        
        print("-" * 100)


def plot_fitness_from_csv(ax, df: pd.DataFrame, gen_line: Optional[int] = None, 
                         log: bool = False, pltmax: bool = True, label: Optional[str] = None, 
                         color: Optional[str] = None, legend: bool = True,
                         xlabel_fontsize: int = 12, ylabel_fontsize: int = 12,
                         tick_fontsize: int = 10):
    """Plot fitness data from CSV DataFrame using aggregated run data."""
    
    # Aggregate data across runs for each generation
    agg_data = aggregate_runs_by_generation(df)
    
    max_fitness_data = agg_data['max_fitness']
    mean_fitness_data = agg_data['mean_fitness']
    
    # Handle infinities and nans
    max_fitness_data[max_fitness_data == -np.inf] = np.nan
    max_fitness_data[max_fitness_data == np.inf] = np.nan
    mean_fitness_data[mean_fitness_data == -np.inf] = np.nan
    mean_fitness_data[mean_fitness_data == np.inf] = np.nan
    
    if log:
        max_fitness_data = -np.log(-max_fitness_data)
        mean_fitness_data = -np.log(-mean_fitness_data)
    
    # Calculate statistics across runs for each generation
    mean_of_means = np.nanmean(mean_fitness_data, axis=1)
    std_of_means = np.nanstd(mean_fitness_data, axis=1)
    mean_of_maxs = np.nanmean(max_fitness_data, axis=1)
    std_of_maxs = np.nanstd(max_fitness_data, axis=1)
    
    generations = np.arange(len(mean_of_means))
    
    # Create labels
    label1 = f"{label} Mean Fitness" if label is not None else 'Mean Fitness'
    label2 = f"{label} Max Fitness" if label is not None else 'Max Fitness'
    
    # Plot mean fitness
    ax.plot(generations, mean_of_means, label=label1 if legend else None, color=color)
    ax.fill_between(generations, mean_of_means - std_of_means, 
                   mean_of_means + std_of_means, alpha=0.2, color=color)
    
    # Plot max fitness if requested
    if pltmax:
        ax.plot(generations, mean_of_maxs, linestyle='--', label=label2 if legend else None, color=color)
        ax.fill_between(generations, mean_of_maxs - std_of_maxs, 
                       mean_of_maxs + std_of_maxs, alpha=0.1, color=color)
    
    # Add generation line if specified
    if gen_line is not None:
        y_max = np.nanmax(mean_of_maxs)
        y_min = np.nanmin(mean_of_means)
        ax.plot([gen_line, gen_line], [y_min, y_max], color="black", linestyle=':')
    
    ax.set_xlabel('Generation', fontsize=xlabel_fontsize)
    ax.set_ylabel('Fitness', fontsize=ylabel_fontsize)
    ax.tick_params(axis='both', which='major', labelsize=tick_fontsize)
    
    if legend:
        ax.legend(fontsize=tick_fontsize)
    ax.grid()
    # ax.set_ylim([np.nanmin(mean_of_means) * 0.95, np.nanmax(mean_of_maxs) * 1.05])


def plot_diversity_from_csv(ax, df: pd.DataFrame, title: str = 'Diversity', 
                           label: Optional[str] = None, color: str = 'b',
                           xlabel_fontsize: int = 12, ylabel_fontsize: int = 12,
                           tick_fontsize: int = 10):
    """Plot diversity data from CSV DataFrame."""
    
    # Aggregate data across runs for each generation
    agg_data = aggregate_runs_by_generation(df)
    diversity_data = agg_data['diversity']  # Shape: (generations, runs)
    
    # Calculate mean and std across runs for each generation
    means = np.nanmean(diversity_data, axis=1)
    stds = np.nanstd(diversity_data, axis=1)
    
    # Handle cases where all values are NaN for a generation
    valid_mask = ~np.isnan(means)
    generations = np.arange(len(means))
    
    # Only plot generations that have valid data
    if np.any(valid_mask):
        ax.plot(generations[valid_mask], means[valid_mask], label=label, color=color)
        ax.fill_between(generations[valid_mask], 
                       (means - stds)[valid_mask], 
                       (means + stds)[valid_mask], 
                       alpha=0.2, color=color)
    
    ax.set_xlabel('Generation', fontsize=xlabel_fontsize)
    ax.set_ylabel('Diversity', fontsize=ylabel_fontsize)
    ax.tick_params(axis='both', which='major', labelsize=tick_fontsize)
    ax.grid(True)
    if label is not None:
        ax.legend()


def plot_single_experiment(experiment_data: Dict[str, pd.DataFrame], 
                          experiment_name: str, save_path: Optional[str] = None,
                          fitness_figsize: tuple = (10, 6), diversity_figsize: tuple = (10, 6),
                          xlabel_fontsize: int = 12, ylabel_fontsize: int = 12,
                          tick_fontsize: int = 10):
    """Create separate plots for fitness and diversity for a single experiment."""
    
    if experiment_name not in experiment_data:
        print(f"No data found for experiment: {experiment_name}")
        return
    
    df = experiment_data[experiment_name]
    
    # Create fitness plot
    fig_fitness, ax_fitness = plt.subplots(1, 1, figsize=fitness_figsize)
    plot_fitness_from_csv(ax_fitness, df, color='red', legend=False,
                         xlabel_fontsize=xlabel_fontsize, ylabel_fontsize=ylabel_fontsize,
                         tick_fontsize=tick_fontsize)
    
    plt.tight_layout()
    
    if save_path:
        fitness_path = os.path.join(save_path, f"{experiment_name}_fitness.png")
        plt.savefig(fitness_path, dpi=300, bbox_inches='tight')
        print(f"Saved fitness plot for {experiment_name}")
    
    # plt.show()
    
    # Create diversity plot
    fig_diversity, ax_diversity = plt.subplots(1, 1, figsize=diversity_figsize)
    plot_diversity_from_csv(ax_diversity, df, color='red', label=None,
                           xlabel_fontsize=xlabel_fontsize, ylabel_fontsize=ylabel_fontsize,
                           tick_fontsize=tick_fontsize)
    
    plt.tight_layout()
    
    if save_path:
        diversity_path = os.path.join(save_path, f"{experiment_name}_diversity.png")
        plt.savefig(diversity_path, dpi=300, bbox_inches='tight')
        print(f"Saved diversity plot for {experiment_name}")
    
    # plt.show()


def plot_grouped_experiments(experiment_data: Dict[str, pd.DataFrame], 
                           experiments_row: List[str], 
                           column_colors: List = ['blue'],
                           save_path: Optional[str] = None,
                           row_name: Optional[str] = None,
                           fitness_figsize: tuple = (10, 6), 
                           diversity_figsize: tuple = (10, 6),
                           xlabel_fontsize: int = 12, 
                           ylabel_fontsize: int = 12,
                           tick_fontsize: int = 10):
    """
    Create separate plots for fitness and diversity for multiple experiments on the same graph.
    Similar to plot_single_experiment but for multiple experiments overlaid.
    """
    
    # Filter experiments that have data
    available_experiments = [exp for exp in experiments_row if exp in experiment_data]
    
    if not available_experiments:
        print(f"No data found for any experiments in row: {experiments_row}")
        return
    
    # Create fitness plot
    fig_fitness, ax_fitness = plt.subplots(1, 1, figsize=fitness_figsize)
    
    for i,exp_name in enumerate(available_experiments):
        df = experiment_data[exp_name]
        
        # Plot fitness with shared color but different labels
        # Temporarily disable automatic y-limits in the plotting function
        plot_fitness_from_csv(ax_fitness, df, label=exp_name, color=column_colors[i], 
                             legend=True,
                             xlabel_fontsize=xlabel_fontsize, 
                             ylabel_fontsize=ylabel_fontsize,
                             tick_fontsize=tick_fontsize)
    
    plt.tight_layout()
    
    # Save fitness plot
    if save_path:
        if row_name:
            fitness_filename = f"{row_name}_grouped_fitness.png"
        else:
            fitness_filename = f"{'_'.join(available_experiments)}_grouped_fitness.png"
        
        fitness_path = os.path.join(save_path, fitness_filename)
        plt.savefig(fitness_path, dpi=300, bbox_inches='tight')
        print(f"Saved grouped fitness plot: {fitness_filename}")
    
    # plt.show()
    
    # Create diversity plot
    fig_diversity, ax_diversity = plt.subplots(1, 1, figsize=diversity_figsize)
    
    for i,exp_name in enumerate(available_experiments):
        df = experiment_data[exp_name]
        
        # Plot diversity with shared color but different labels
        plot_diversity_from_csv(ax_diversity, df, label=exp_name, color=column_colors[i],
                              xlabel_fontsize=xlabel_fontsize, 
                              ylabel_fontsize=ylabel_fontsize,
                              tick_fontsize=tick_fontsize)
    
    plt.tight_layout()
    
    # Save diversity plot
    if save_path:
        if row_name:
            diversity_filename = f"{row_name}_grouped_diversity.png"
        else:
            diversity_filename = f"{'_'.join(available_experiments)}_grouped_diversity.png"
        
        diversity_path = os.path.join(save_path, diversity_filename)
        plt.savefig(diversity_path, dpi=300, bbox_inches='tight')
        print(f"Saved grouped diversity plot: {diversity_filename}")
    
    # plt.show()


def plot_comparison(experiment_data: Dict[str, pd.DataFrame], 
                   experiments_to_compare: List[str], 
                   save_path: Optional[str] = None,
                   figsize: tuple = (12, 8),
                   xlabel_fontsize: int = 12, ylabel_fontsize: int = 12,
                   tick_fontsize: int = 10):
    """Create separate comparison plots for fitness, diversity, and max fitness."""
    
    colors = ['#4477AA', '#EE6677', '#228833', '#CCBB44', '#AA3377', '#66CCEE', '#BBBBBB']

    # Create fitness comparison plot
    fig_fitness, ax_fitness = plt.subplots(1, 1, figsize=figsize)
    
    for i, exp_name in enumerate(experiments_to_compare):
        if exp_name in experiment_data:
            color = colors[i % len(colors)]
            df = experiment_data[exp_name]
            
            # Plot fitness comparison (mean fitness only)
            plot_fitness_from_csv(ax_fitness, df, label=exp_name, color=color, 
                                legend=True, pltmax=False,
                                xlabel_fontsize=xlabel_fontsize, 
                                ylabel_fontsize=ylabel_fontsize,
                                tick_fontsize=tick_fontsize)
    
    plt.tight_layout()

    if save_path:
        plt.savefig(os.path.join(save_path, "fitness_comparison.png"),
                   dpi=300, bbox_inches='tight')
        print("Saved fitness comparison plot")

    # plt.show()

    # Create diversity comparison plot
    fig_diversity, ax_diversity = plt.subplots(1, 1, figsize=figsize)

    for i, exp_name in enumerate(experiments_to_compare):
        if exp_name in experiment_data:
            color = colors[i % len(colors)]
            df = experiment_data[exp_name]

            # Plot diversity comparison
            plot_diversity_from_csv(ax_diversity, df, label=exp_name, color=color,
                                  xlabel_fontsize=xlabel_fontsize,
                                  ylabel_fontsize=ylabel_fontsize,
                                  tick_fontsize=tick_fontsize)

    plt.tight_layout()
    
    if save_path:
        plt.savefig(os.path.join(save_path, "diversity_comparison.png"), 
                   dpi=300, bbox_inches='tight')
        print("Saved diversity comparison plot")
    
    # plt.show()
    
    # Create max fitness comparison plot
    fig_max_fitness, ax_max_fitness = plt.subplots(1, 1, figsize=figsize)
    
    for i, exp_name in enumerate(experiments_to_compare):
        if exp_name in experiment_data:
            color = colors[i % len(colors)]
            df = experiment_data[exp_name]
            
            # Aggregate data and plot max fitness only
            agg_data = aggregate_runs_by_generation(df)
            max_fitness_data = agg_data['max_fitness']
            
            # Handle infinities and nans
            max_fitness_data[max_fitness_data == -np.inf] = np.nan
            max_fitness_data[max_fitness_data == np.inf] = np.nan
            
            # Calculate statistics across runs for each generation
            mean_of_maxs = np.nanmean(max_fitness_data, axis=1)
            std_of_maxs = np.nanstd(max_fitness_data, axis=1)
            
            generations = np.arange(len(mean_of_maxs))
            
            # Plot max fitness
            ax_max_fitness.plot(generations, mean_of_maxs, label=exp_name, color=color)
            ax_max_fitness.fill_between(generations, mean_of_maxs - std_of_maxs, 
                                      mean_of_maxs + std_of_maxs, alpha=0.2, color=color)
    
    ax_max_fitness.set_xlabel('Generation', fontsize=xlabel_fontsize)
    ax_max_fitness.set_ylabel('Max Fitness', fontsize=ylabel_fontsize)
    ax_max_fitness.tick_params(axis='both', which='major', labelsize=tick_fontsize)
    ax_max_fitness.legend(fontsize=tick_fontsize)
    ax_max_fitness.grid()
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(os.path.join(save_path, "max_fitness_comparison.png"), 
                   dpi=300, bbox_inches='tight')
        print("Saved max fitness comparison plot")
    
    # plt.show()


def plot_median_max_fitness(experiment_data: Dict[str, pd.DataFrame],
                           experiments_to_compare: List[str],
                           colors: List[str],
                           save_path: Optional[str] = None,
                           figsize: tuple = (10, 6),
                           xlabel_fontsize: int = 12, ylabel_fontsize: int = 12,
                           tick_fontsize: int = 10):
    """Plot median max fitness across runs with IQR shading."""
    fig, ax = plt.subplots(1, 1, figsize=figsize)

    for i, exp_name in enumerate(experiments_to_compare):
        if exp_name not in experiment_data:
            continue
        color = colors[i % len(colors)]
        df = experiment_data[exp_name]

        agg_data = aggregate_runs_by_generation(df)
        max_fitness_data = agg_data['max_fitness']

        # Handle infinities and nans
        max_fitness_data[max_fitness_data == -np.inf] = np.nan
        max_fitness_data[max_fitness_data == np.inf] = np.nan

        # Calculate median and IQR across runs for each generation
        median = np.nanmedian(max_fitness_data, axis=1)
        q25 = np.nanpercentile(max_fitness_data, 25, axis=1)
        q75 = np.nanpercentile(max_fitness_data, 75, axis=1)

        generations = np.arange(len(median))

        ax.plot(generations, median, label=exp_name, color=color)
        ax.fill_between(generations, q25, q75, alpha=0.2, color=color)

    ax.set_xlabel('Generation', fontsize=xlabel_fontsize)
    ax.set_ylabel('Max Fitness (Median)', fontsize=ylabel_fontsize)
    ax.tick_params(axis='both', which='major', labelsize=tick_fontsize)
    ax.legend(fontsize=tick_fontsize)
    ax.grid()

    plt.tight_layout()

    if save_path:
        plt.savefig(os.path.join(save_path, "median_max_fitness_comparison.png"),
                    dpi=300, bbox_inches='tight')
        print("Saved median max fitness comparison plot")


def generate_summary_statistics(experiment_data: Dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Generate summary statistics for all experiments."""
    
    summary_data = []
    
    for exp_name, df in experiment_data.items():
        # Get final generation data
        final_gen = df['generation'].max()
        final_data = df[df['generation'] == final_gen]
        
        # Calculate summary statistics
        summary = {
            'experiment': exp_name,
            'total_runs': len(df['run'].unique()),
            'total_generations': final_gen + 1,
            'final_max_fitness_mean': final_data['max_fitness'].mean(),
            'final_max_fitness_std': final_data['max_fitness'].std(),
            'final_mean_fitness_mean': final_data['mean_fitness'].mean(),
            'final_mean_fitness_std': final_data['mean_fitness'].std(),
            'final_diversity_mean': final_data['diversity'].mean(),
            'final_diversity_std': final_data['diversity'].std(),
        }
        
        summary_data.append(summary)
    
    return pd.DataFrame(summary_data)


def run_significance_tests(experiment_data: Dict[str, pd.DataFrame], genome_names: List[str]) -> Dict:
    """
    Run pairwise Mann-Whitney U tests on final-generation fitness values between genomes.
    Returns results with median values, U-statistic, p-values, and significance flags.
    """
    # Extract final-generation values per genome
    final_values = {}
    for name in genome_names:
        if name not in experiment_data:
            continue
        df = experiment_data[name]
        final_gen = df['generation'].max()
        final_data = df[df['generation'] == final_gen]
        final_values[name] = {
            'max_fitness': final_data['max_fitness'].values,
            'mean_fitness': final_data['mean_fitness'].values,
        }

    available = [n for n in genome_names if n in final_values]
    pairs = list(combinations(available, 2))
    n_comparisons = len(pairs)

    results = {}
    for metric in ['max_fitness', 'mean_fitness']:
        results[metric] = []
        for a, b in pairs:
            vals_a = final_values[a][metric]
            vals_b = final_values[b][metric]

            # Filter out NaN values
            vals_a = vals_a[~np.isnan(vals_a)]
            vals_b = vals_b[~np.isnan(vals_b)]

            if len(vals_a) < 2 or len(vals_b) < 2:
                results[metric].append({
                    'genome_a': a, 'genome_b': b,
                    'median_a': np.nan, 'median_b': np.nan,
                    'u_stat': np.nan, 'p_value': np.nan,
                    'p_corrected': np.nan, 'significant': False,
                })
                continue

            u_stat, p_value = mannwhitneyu(vals_a, vals_b, alternative='two-sided')
            p_corrected = min(p_value * n_comparisons, 1.0)

            results[metric].append({
                'genome_a': a,
                'genome_b': b,
                'median_a': np.median(vals_a),
                'median_b': np.median(vals_b),
                'u_stat': u_stat,
                'p_value': p_value,
                'p_corrected': p_corrected,
                'significant': p_corrected < 0.05,
            })

    return results


def print_significance_table(results: Dict, task_name: str = ""):
    """Print formatted significance test results for each metric."""
    prefix = f" - {task_name}" if task_name else ""
    for metric in ['max_fitness', 'mean_fitness']:
        metric_label = metric.replace('_', ' ').title()
        print(f"\nSIGNIFICANCE TESTS{prefix} - {metric_label} (Final Generation)")
        print("-" * 110)
        print(f"{'Comparison':<30} | {'Median A':>10} | {'Median B':>10} | {'U-stat':>10} | {'p-value':>10} | {'p-corrected':>12} | {'Significant':>11}")
        print("-" * 110)
        for r in results[metric]:
            label = f"{r['genome_a']} vs {r['genome_b']}"
            sig = "Yes" if r['significant'] else "No"
            print(f"{label:<30} | {r['median_a']:>10.4f} | {r['median_b']:>10.4f} | {r['u_stat']:>10.1f} | {r['p_value']:>10.4f} | {r['p_corrected']:>12.4f} | {sig:>11}")
        print("-" * 110)


def generate_significance_latex_table(results: Dict, save_path: str, task_name: str = ""):
    """Generate LaTeX table of significance test results and save to file."""
    latex_lines = []
    for metric in ['max_fitness', 'mean_fitness']:
        metric_label = metric.replace('_', ' ').title()
        label_suffix = metric.replace('_', '')
        task_suffix = f"_{task_name}" if task_name else ""

        latex_lines.append(f"\\begin{{table}}[htbp]")
        latex_lines.append(f"\\centering")
        latex_lines.append(f"\\caption{{Significance Tests - {metric_label}{' (' + task_name + ')' if task_name else ''}}}")
        latex_lines.append(f"\\label{{tab:significance_{label_suffix}{task_suffix}}}")
        latex_lines.append(f"\\begin{{tabular}}{{|l|c|c|c|c|c|c|}}")
        latex_lines.append(f"\\hline")
        latex_lines.append(f"\\textbf{{Comparison}} & \\textbf{{Median A}} & \\textbf{{Median B}} & \\textbf{{U-stat}} & \\textbf{{p-value}} & \\textbf{{p-corrected}} & \\textbf{{Sig.}} \\\\")
        latex_lines.append(f"\\hline")

        for r in results[metric]:
            a_clean = r['genome_a'].replace('_', '\\_')
            b_clean = r['genome_b'].replace('_', '\\_')
            sig = "Yes" if r['significant'] else "No"
            latex_lines.append(
                f"{a_clean} vs {b_clean} & {r['median_a']:.4f} & {r['median_b']:.4f} & "
                f"{r['u_stat']:.1f} & {r['p_value']:.4f} & {r['p_corrected']:.4f} & {sig} \\\\"
            )
            latex_lines.append("\\hline")

        latex_lines.append("\\end{tabular}")
        latex_lines.append("\\end{table}")
        latex_lines.append("")

    latex_table = "\n".join(latex_lines)
    filepath = os.path.join(save_path, "significance_table.tex")
    with open(filepath, 'w') as f:
        f.write(latex_table)
    print(f"LaTeX significance table saved to: {filepath}")


def print_cross_task_summary(all_task_results: Dict[str, Dict], genome_names: List[str], save_path: Optional[str] = None):
    """
    Print cross-task pairwise win matrix and combined p-values (Fisher's method).

    Args:
        all_task_results: Dict mapping task_name -> significance test results
        genome_names: List of genome names
        save_path: Optional path to save LaTeX tables
    """
    available = genome_names
    pairs = list(combinations(available, 2))
    tasks = list(all_task_results.keys())
    n_tasks = len(tasks)

    for metric in ['max_fitness', 'mean_fitness']:
        metric_label = metric.replace('_', ' ').title()

        # Build win matrix: wins[a][b] = number of tasks where a significantly beats b
        wins = {g: {g2: 0 for g2 in available} for g in available}

        # Collect p-values per pair across tasks for Fisher's method
        pair_pvalues = {(a, b): [] for a, b in pairs}

        for task_name, results in all_task_results.items():
            for r in results[metric]:
                a, b = r['genome_a'], r['genome_b']
                if not np.isnan(r['p_value']):
                    pair_pvalues[(a, b)].append(r['p_value'])
                if r['significant']:
                    if r['median_a'] > r['median_b']:
                        wins[a][b] += 1
                    elif r['median_b'] > r['median_a']:
                        wins[b][a] += 1

        # Print win matrix
        print(f"\nCROSS-TASK PAIRWISE WIN MATRIX - {metric_label}")
        print("-" * (25 + 15 * len(available)))
        header = f"{'':>20}" + "".join(f"{g:>15}" for g in available)
        print(header)
        for a in available:
            row = f"{a:>20}"
            for b in available:
                if a == b:
                    row += f"{'—':>15}"
                else:
                    row += f"{wins[a][b]}/{n_tasks}".rjust(15)
            print(row)
        print("-" * (25 + 15 * len(available)))

        # Combined p-values (Fisher's method)
        print(f"\nCOMBINED P-VALUES (Fisher's method) - {metric_label}")
        print("-" * 70)
        print(f"{'Comparison':<30} | {'Combined p-value':>16} | {'Significant':>11}")
        print("-" * 70)

        fisher_results = []
        for a, b in pairs:
            pvals = pair_pvalues[(a, b)]
            if len(pvals) >= 2:
                _, combined_p = combine_pvalues(pvals, method='fisher')
            elif len(pvals) == 1:
                combined_p = pvals[0]
            else:
                combined_p = np.nan

            sig = "Yes" if combined_p < 0.05 else "No"
            label = f"{a} vs {b}"
            print(f"{label:<30} | {combined_p:>16.6f} | {sig:>11}")
            fisher_results.append({
                'genome_a': a, 'genome_b': b,
                'combined_p': combined_p,
                'significant': combined_p < 0.05,
            })
        print("-" * 70)

        # Save LaTeX version
        if save_path:
            _save_cross_task_latex(wins, fisher_results, available, n_tasks, metric, metric_label, save_path)


def _save_cross_task_latex(wins, fisher_results, available, n_tasks, metric, metric_label, save_path):
    """Save cross-task significance results as LaTeX tables."""
    latex_lines = []
    label_suffix = metric.replace('_', '')

    # Win matrix table
    latex_lines.append("\\begin{table}[htbp]")
    latex_lines.append("\\centering")
    latex_lines.append(f"\\caption{{Cross-Task Pairwise Win Matrix - {metric_label}}}")
    latex_lines.append(f"\\label{{tab:win_matrix_{label_suffix}}}")
    col_spec = "|l|" + "c|" * len(available)
    latex_lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
    latex_lines.append("\\hline")
    header = " & ".join([""] + [g.replace('_', '\\_') for g in available]) + " \\\\"
    latex_lines.append(header)
    latex_lines.append("\\hline")
    for a in available:
        cells = [a.replace('_', '\\_')]
        for b in available:
            if a == b:
                cells.append("---")
            else:
                cells.append(f"{wins[a][b]}/{n_tasks}")
        latex_lines.append(" & ".join(cells) + " \\\\")
        latex_lines.append("\\hline")
    latex_lines.append("\\end{tabular}")
    latex_lines.append("\\end{table}")
    latex_lines.append("")

    # Fisher's method table
    latex_lines.append("\\begin{table}[htbp]")
    latex_lines.append("\\centering")
    latex_lines.append(f"\\caption{{Combined P-Values (Fisher's Method) - {metric_label}}}")
    latex_lines.append(f"\\label{{tab:fisher_{label_suffix}}}")
    latex_lines.append("\\begin{tabular}{|l|c|c|}")
    latex_lines.append("\\hline")
    latex_lines.append("\\textbf{Comparison} & \\textbf{Combined p-value} & \\textbf{Significant} \\\\")
    latex_lines.append("\\hline")
    for r in fisher_results:
        a_clean = r['genome_a'].replace('_', '\\_')
        b_clean = r['genome_b'].replace('_', '\\_')
        sig = "Yes" if r['significant'] else "No"
        latex_lines.append(f"{a_clean} vs {b_clean} & {r['combined_p']:.6f} & {sig} \\\\")
        latex_lines.append("\\hline")
    latex_lines.append("\\end{tabular}")
    latex_lines.append("\\end{table}")

    filepath = os.path.join(save_path, "cross_task_significance.tex")
    with open(filepath, 'w') as f:
        f.write("\n".join(latex_lines))
    print(f"LaTeX cross-task significance tables saved to: {filepath}")


def main():
    """Main function to load data and create plots for v2 per-task comparisons."""

    base_dir = "/media/jed/My Passport/airevolve030326/v2"
    tasks = ["backandforth", "figure8", "circle"]
    experiment_names = ["spherical", "cppn", "hybrid_cppn"]
    column_colors = ['#4477AA', '#EE6677', '#228833']  # Tol bright: blue, rose, green

    # Plot customization options
    fitness_figsize = (10, 6)
    diversity_figsize = (10, 6)
    comparison_figsize = (12, 8)
    xlabel_fontsize = 30
    ylabel_fontsize = 30
    tick_fontsize = 25

    all_task_significance = {}

    for task in tasks:
        print(f"\n{'='*60}")
        print(f"Task: {task}")
        print(f"{'='*60}")

        data_dir = os.path.join(base_dir, task)
        save_dir = os.path.join(base_dir, "plots", task)
        os.makedirs(save_dir, exist_ok=True)

        # Load all genotype data for this task
        print("Loading experiment data...")
        experiment_data = load_experiment_data(data_dir, experiment_names)

        if not experiment_data:
            print(f"No experiment data loaded for task {task}. Skipping.")
            continue

        # Calculate and print fitness improvements
        print("\nCalculating fitness improvements...")
        improvement_stats = calculate_fitness_improvement(experiment_data)
        print_fitness_improvement_summary(improvement_stats)

        # Generate and save LaTeX table
        if improvement_stats:
            print("\nGenerating LaTeX table...")
            latex_table = generate_latex_table(improvement_stats, save_dir)
            print("\nLaTeX Table Code:")
            print("="*50)
            print(latex_table)
            print("="*50)

        # Save improvement statistics to CSV
        if improvement_stats:
            improvement_df = pd.DataFrame(improvement_stats).T
            improvement_df.to_csv(os.path.join(save_dir, "fitness_improvement_stats.csv"))

        # Generate summary statistics
        print("\nGenerating summary statistics...")
        summary_stats = generate_summary_statistics(experiment_data)
        print(summary_stats)
        summary_stats.to_csv(os.path.join(save_dir, "experiment_summary.csv"), index=False)

        # Run significance tests
        print("\nRunning significance tests...")
        sig_results = run_significance_tests(experiment_data, experiment_names)
        print_significance_table(sig_results, task_name=task)
        generate_significance_latex_table(sig_results, save_dir, task_name=task)
        all_task_significance[task] = sig_results

        # Individual experiment plots
        print("\nCreating individual experiment plots...")
        for exp_name in experiment_data.keys():
            plot_single_experiment(experiment_data, exp_name, save_dir,
                                 fitness_figsize=fitness_figsize,
                                 diversity_figsize=diversity_figsize,
                                 xlabel_fontsize=xlabel_fontsize,
                                 ylabel_fontsize=ylabel_fontsize,
                                 tick_fontsize=tick_fontsize)

        # Grouped genotype comparison (all 3 genotypes overlaid)
        print("\nCreating grouped genotype comparison plots...")
        plot_grouped_experiments(experiment_data, experiment_names,
                               column_colors=column_colors,
                               save_path=save_dir,
                               row_name=task,
                               fitness_figsize=fitness_figsize,
                               diversity_figsize=diversity_figsize,
                               xlabel_fontsize=xlabel_fontsize,
                               ylabel_fontsize=ylabel_fontsize,
                               tick_fontsize=tick_fontsize)

        # Comparison plots (fitness, diversity, max fitness)
        print("\nCreating comparison plots...")
        available_experiments = list(experiment_data.keys())
        plot_comparison(experiment_data, available_experiments, save_dir,
                       figsize=comparison_figsize,
                       xlabel_fontsize=xlabel_fontsize,
                       ylabel_fontsize=ylabel_fontsize,
                       tick_fontsize=tick_fontsize)

        # Median max fitness plot
        print("\nCreating median max fitness plot...")
        plot_median_max_fitness(experiment_data, experiment_names, column_colors,
                               save_path=save_dir, figsize=fitness_figsize,
                               xlabel_fontsize=xlabel_fontsize,
                               ylabel_fontsize=ylabel_fontsize,
                               tick_fontsize=tick_fontsize)

    # Cross-task significance summary
    if all_task_significance:
        print(f"\n{'='*60}")
        print("CROSS-TASK SIGNIFICANCE SUMMARY")
        print(f"{'='*60}")
        cross_task_save_dir = os.path.join(base_dir, "plots")
        os.makedirs(cross_task_save_dir, exist_ok=True)
        print_cross_task_summary(all_task_significance, experiment_names, save_path=cross_task_save_dir)

    print("Plotting complete!")


if __name__ == "__main__":
    main()